runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT demo.wsgi

runtime_config:
  python_version: 3.4


beta_settings:
    cloud_sql_instances: "root-welder-193802:us-central1:demo-cloud-sql"

env_variables:
  DB_NAME: app
  DB_USER: app_user
  DB_PASSWORD: user123

manual_scaling:
  instances: 3
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10


